# ===================================
#  Relation Behavior Config
# ===================================

product_items:
    label: Product Items
    view:
        list: $/marty/nexgenrifle/models/productitem/columns.yaml
        toolbarButtons: create|delete
    form:
        fields: $/marty/nexgenrifle/models/productitem/fields.yaml
    manage:
        showSearch: true
        recordsPerPage: 10
        showCheckboxes: true

product_category:
    label: Product Category
    view:
        list: $/marty/nexgenrifle/models/productcategory/columns.yaml
        toolbarButtons: link|unlink
    form:
        fields: $/marty/nexgenrifle/models/productcategory/fields.yaml
    manage:
        showSearch: true
        recordsPerPage: 10

supplier:
    label: Supplier
    view:
        list: $/marty/nexgenrifle/models/supplier/columns.yaml
        toolbarButtons: link|unlink
    form:
        fields: $/marty/nexgenrifle/models/supplier/fields.yaml
    manage:
        showSearch: true
        recordsPerPage: 10
