# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/marty/aisolutions/models/aimessage/columns.yaml

# Model Class name
modelClass: Marty\AiSolutions\Models\AIMessage

# List Title
title: Manage AI Messages

# Link URL for each record
recordUrl: marty/aisolutions/messages/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column headers
showSorting: true

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
