# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/marty/nexgenrifle/models/productcategory/columns.yaml

# Model Class name
modelClass: Marty\NexGenRifle\Models\ProductCategory

# List Title
title: Manage Product Categories

# Link URL for each record
recordUrl: marty/nexgenrifle/categories/update/product/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Show checkboxes
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    buttons: product_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Default sorting
defaultSort:
    column: order
    direction: asc
