# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Build Category

# Model Form Field configuration
form: $/nexgenrifle/nexgenrifle/models/buildcategory/fields.yaml

# Model Class name
modelClass: NexgenRifle\NexgenRifle\Models\BuildCategory

# Default redirect location
defaultRedirect: nexgenrifle/nexgenrifle/buildcategory

# Create page
create:
    title: backend::lang.form.create_title
    redirect: nexgenrifle/nexgenrifle/buildcategory/update/:id
    redirectClose: nexgenrifle/nexgenrifle/buildcategory

# Update page
update:
    title: backend::lang.form.update_title
    redirect: nexgenrifle/nexgenrifle/buildcategory
    redirectClose: nexgenrifle/nexgenrifle/buildcategory

# Preview page
preview:
    title: backend::lang.form.preview_title
