# ===================================
#  Relation Behavior Config
# ===================================

messages:
    label: Messages
    view:
        list: $/marty/aisolutions/models/aimessage/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/marty/aisolutions/models/aimessage/fields.yaml
        recordsPerPage: 10

profile_type:
    label: Profile Type
    view:
        list: $/marty/nexgenrifle/models/profiletype/columns.yaml
        toolbarButtons: link|unlink
    manage:
        list: $/marty/nexgenrifle/models/profiletype/columns.yaml
        form: $/marty/nexgenrifle/models/profiletype/fields.yaml

user:
    label: User
    view:
        list: ~/modules/backend/models/user/columns.yaml
        toolbarButtons: link|unlink
    manage:
        list: ~/modules/backend/models/user/columns.yaml
        form: ~/modules/backend/models/user/fields.yaml
