# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/marty/nexgenrifle/models/profiletype/columns.yaml

# Model Class name
modelClass: Marty\NexGenRifle\Models\ProfileType

# List Title
title: Manage Profile Types

# Link URL for each record
recordUrl: marty/nexgenrifle/profiles/update/types/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Show checkboxes
showCheckboxes: true

# Default sorting
defaultSort:
    column: order
    direction: asc

# Toolbar widget configuration
toolbar:
    buttons: types_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
